[data]
seed = 0
cache = true
path = ":data/car_regression"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "standard"

[dnnr]
n_neighbors = [
    1,
    129,
]
n_derivative_neighbors = [
    16,
    144,
    20,
]
scalings_dir = "dnnr/precomputed_scaling/car_regression/loo"
