[data]
seed = 0
cache = true
path = ":data/microsoft"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[dnnr]
n_neighbors = [
    1,
    129,
]
n_derivative_neighbors = [
    272,
    1904,
    14,
]
scalings_dir = "dnnr/precomputed_scaling/microsoft/loo"
